config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorship
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  scope :all_by_tags, lambda { |tags|
    questions = includes(:user)
    questions = if tags
                  questions.joins(:tags).where(tags:).preload(:tags)
                else
                  questions.includes(:question_tags, :tags)
                end

    questions.order(created_at: :desc)
  }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsAnswers

  before_action :require_authentication, except: %i[index show]
  before_action :set_question!, only: %i[edit update destroy show]
  before_action :authorize_question!
  after_action :verify_authorized

  def index
    @tags = Tag.where(id: params[:tag_ids]) if params[:tag_ids]
    @pagy, @questions = pagy Question.all_by_tags(@tags), link_extra: 'data-turbo-frame="pagination_pagy"'
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      respond_to do |format|
        format.html do
          flash[:success] = t('flash_messages.success.questions.created')
          redirect_to questions_path
        end

        format.turbo_stream do
          @question = @question.decorate
          flash.now[:success] = t('flash_messages.success.questions.created')
        end
      end
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update question_params
      respond_to do |format|
        format.html do
          flash[:success] = t('flash_messages.success.questions.updated')
          redirect_to questions_path
        end

        format.turbo_stream do
          @question = @question.decorate
          flash.now[:success] = t('flash_messages.success.questions.updated')
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html do
        flash[:success] = t('flash_messages.success.questions.deleted')
        redirect_to questions_path, status: :see_other
      end

      format.turbo_stream do
        flash.now[:success] = t('flash_messages.success.questions.deleted')
      end
    end
  end

  def show
    load_question_answers
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_question!
    @question = Question.find params[:id]
  end

  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_form.html.erb
<%= turbo_frame_tag question do %>
  <%= form_with model: @question do |f| %>
    <%= render "shared/errors", object: @question %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, placeholder: t("questions.new.placeholder"), class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :tags %>
      </div>

      <div class="col-sm-10">
        <%= f.collection_select :tag_ids, @question.tags, :id, :title, {}, multiple: true,
                                class: "js-multiple-select",
                                data: { "ajax-url": "/api/tags" } %>
      </div>
    </div>

    <div class="my-3">
      <%= f.submit t("general.btn.submit_question"), class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/questions/_question.html.erb
<%= turbo_frame_tag question do %>
  <article class="card my-3">
    <section class="card-header">
      <%= question.user.gravatar %>
      <%= question.user.name_or_email %>
    </section>

    <div class="card-body">
      <h2><%= link_to question.title, question_path(question),
                      data: { turbo_frame: "_top" } %></h2>

      <section class="card-text">
        <%= tag.time datetime: question.formatted_created_at do %>
          <small><%= question.formatted_created_at %></small>
        <% end %>


        <div class="my-2">
          <%= render question.tags %>
        </div>

        <p class="my-2">
          <%= sanitize question.body %>
        </p>
      </section>

      <% if policy(question).edit? %>
        <%= link_to t("general.btn.edit"), edit_question_path(question), class: "btn btn-secondary" %>
      <% end %>

      <% if policy(question).destroy? %>
        <%= link_to t("general.btn.delete"), question_path(question), class: "btn btn-danger",
                    data: { turbo_method: :delete, turbo_confirm: t("general.confirm.delete") } %>
      <% end %>
    </div>
  </article>
<% end %>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.prepend "questions", render(@question) %>
<%= prepend_flash %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>
<%= prepend_flash %>

app/views/questions/edit.html.erb
<% provide :page_title, "Edit question" %>
<% currently_at t("menu.questions") %>

<h1 class="mb-4"><%= t(".title") %></h1>

<%= render "form", question: @question %>

app/views/questions/index.html.erb
<% provide :page_title, "Questions" %>
<% currently_at t("menu.questions") %>

<h1 class="mb-4"><%= t(".header") %></h1>

<section class="mb-5">
  <h2><%= t '.search_by_tags' %></h2>

  <%= form_with url: questions_path, method: :get do |f| %>
    <div class="mb-3">
      <%= f.collection_select :tag_ids, (@tags || []), :id, :title, { selected: params[:tag_ids] },
                              multiple: true, required: true,
                              class: 'js-multiple-select js-ajax-select w-100',
                              data: { 'ajax-url': '/api/tags' } %>
    </div>

    <%= f.submit t('general.btn.search'), class: 'btn btn-primary' %>
  <% end %>
</section>

<% if policy(:question).new? %>
  <%= link_to t("general.btn.new_question"), new_question_path,
              class: "btn btn-primary btn-lg mb-3",
              data: { turbo_frame: dom_id(Question.new) } %>

  <dev class="my-3">
    <%= turbo_frame_tag Question.new %>
  </dev>
<% end %>

<%= turbo_frame_tag "pagination_pagy" do %>
  <%= pagination @pagy %>

  <%= turbo_frame_tag "questions" do %>
    <%= render @questions %>
  <% end %>

  <%= pagination @pagy %>
<% end %>

app/views/questions/new.html.erb
<% provide :page_title, "New question" %>
<% currently_at t("menu.questions") %>

<h1 class="mb-4"><%= t(".title") %></h1>

<%= render "form", question: @question %>

app/views/questions/show.html.erb
<% provide :page_title, "Question info" %>
<% currently_at t("menu.questions") %>

<article class="mb-3">
  <%= render @question %>
</article>

<%= render "comments/commentable", commentable: @question, comment: @comment %>

<h2 class="my-3"><%= t(".first_header") %></h2>

<%= render "answers/form" %>

<h2 class="mt-5 mb-3"><%= t(".second_header") %></h2>

<%= pagination @pagy %>

<%= turbo_frame_tag "answers" do %>
  <%= render partial: "answers/answer", collection: @answers,
             as: :answer, locals: { question: @question } %>
<% end %>

<%= pagination @pagy %>

app/views/questions/update.turbo_stream.erb
<%= turbo_stream.replace @question, render(@question) %>
<%= prepend_flash %>