config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Authorship
  include Commentable

  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include QuestionsAnswers
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create
  before_action :authorize_answer!
  after_action :verify_authorized

  def create
    @answer = @question.answers.build answer_create_params

    if @answer.save
      respond_to do |format|
        format.html do
          flash[:success] = t('flash_messages.success.answers.created')
          redirect_to question_path(@question)
        end

        format.turbo_stream do
          @answer = @answer.decorate
          flash.now[:success] = t('flash_messages.success.answers.created')
        end
      end
    else
      load_question_answers(do_render: true)
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html do
        flash[:success] = t('flash_messages.success.answers.deleted')
        redirect_to questions_path(@question), status: :see_other
      end

      format.turbo_stream do
        flash.now[:success] = t('flash_messages.success.answers.deleted')
      end
    end
  end

  def edit; end

  def update
    if @answer.update answer_update_params
      respond_to do |format|
        format.html do
          flash[:success] = t('flash_messages.success.answers.updated')
          redirect_to question_path(@question, anchor: dom_id(@answer))
        end

        format.turbo_stream do
          @answer = @answer.decorate
          flash.now[:success] = t('flash_messages.success.answers.updated')
        end
      end
    else
      render :edit
    end
  end

  private

  def answer_create_params
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end

  def authorize_answer!
    authorize(@answer || Answer)
  end
end

app/views/answers/_answer.html.erb
<%= turbo_frame_tag answer do %>
  <%= tag.article class: "mb-3 card border-0 border-top" do %>
    <div class="row g-0">
      <div class="col-sm-auto text-sm-center align-self-center">
        <%= answer.user.gravatar size: 50, css_class: "d-block" %>
        <%= answer.user.name_or_email %>
      </div>
      <div class="col-sm">
        <div class="card-body">
          <section class="card-text mb-3">
            <div class="col-sm-9">
              <small>
                <time datetime="<%= answer.formatted_created_at %>">
                  <%= answer.formatted_created_at %>
                </time>
              </small>

              <div class="mt-2">
                <%= sanitize answer.body %>
              </div>
            </div>
          </section>

          <% if policy(answer).edit? %>
            <%= link_to t("general.btn.edit"), edit_question_answer_path(question, answer),
                        class: "btn btn-secondary btn-sm" %>
          <% end %>

          <% if policy(answer).destroy? %>
            <%= link_to t("general.btn.delete"), question_answer_path(question, answer),
                        class: "btn btn-danger btn-sm",
                        data: { turbo_method: :delete, turbo_confirm: t("general.confirm.delete") } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>


  <%= render "comments/commentable", commentable: answer, comment: @comment %>
<% end %>

app/views/answers/_form.html.erb
<%= turbo_frame_tag @answer do %>
  <%= form_with model: [@question, @answer] do |f| %>
    <%= render "shared/errors", object: @answer %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control", required: true %>
      </div>
    </div>

    <%= f.submit t("general.btn.submit_answer"), class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.prepend "answers", render(@answer, question: @answer.question) %>
<%= prepend_flash %>

app/views/answers/destroy.turbo_stream.erb
<%= turbo_stream.remove @answer %>
<%= prepend_flash %>

app/views/answers/edit.html.erb
<% provide :page_title, "Edit answer" %>
<% currently_at t("questions.index.header") %>

<h1 class="mb-4"><%= t("answers.edit.title") %></h1>

<%= render "form" %>

app/views/answers/update.turbo_stream.erb
<%= turbo_stream.replace @answer, render(@answer, question: @answer.question) %>
<%= prepend_flash %>